---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Kolektif dert aparatı - derdini sikiyim butonu şurda bi yerde olacaktı"
keywords:    "derdini sikiyim butonu, derdini sikeyim butonu"
description: "Dertsiz başlarına dert arayanlara yollayabileceğiniz bir buton, first world problem, dertleşme ortamı. Derdinizi yazmak derman bulmanın yarısıdır."
source_link: "https://derdinisikiyim.com"
favicon:     "http://faviconist.com/icons/9f484b19371bf470610524f05d2b7b79/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-63953051-1


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
